### ISSUE TITLE
A better UI

### ISSUE THREAD

**Issue by iddu01linux** [HollowTechnology/Launchit#3]
We need a better UI for Launchit, Launchit for gamers, and Launchit Pro (when its made)

**Comment by nehasaleemdesai** [comment]
Hello! 

I’ve made some minor updates to the project and have submitted a pull request. If you have any specific UI vision or need further changes, I’d be happy to help.

Best,
Neha

**Comment by iddu01linux** [comment]
I have merged the branches, thanks!
